#include <stdio.h>

int main() {
    char nome[20];
    char codigo[20];
    char estado[10];
    int populacao;
    float area;
    float pib;
    int pontos;
    char nome1[20];
    char codigo1[20];
    char estado1[10];
    int populacao1;
    float area1;
    float pib1;
    int pontos1;
    printf ("Digite os dados da Carta 01 \n");
    printf("Digite o Estado: \n");
    scanf("%s",&estado);
    printf("Digite o código: \n");
    scanf("%s",&codigo);
    printf("Digite o nome da cidade: \n");
    scanf("%s",&nome);
    printf("Digite o número da população: \n");
    scanf("%d",&populacao);
    printf("Digite a área territorial: \n");
    scanf("%f",&area);
    printf("Digite o PIB: \n");
    scanf("%f",&pib);
    printf("Digite a Quantidade de pontos turísticos: \n");
    scanf("%d",&pontos);
    printf ("Digite os dados da Carta 02 \n");
    printf("Digite o Estado: \n");
    scanf("%s",&estado1);
    printf("Digite o código: \n");
    scanf("%s",&codigo1);
    printf("Digite o nome da cidade: \n");
    scanf("%s",&nome1);
    printf("Digite o número da população: \n");
    scanf("%d",&populacao1);
    printf("Digite a área territorial: \n");
    scanf("%f",&area1);
    printf("Digite o PIB: \n");
    scanf("%f",&pib1);
    printf("Digite a Quantidade de pontos turísticos: \n");
    scanf("%d",&pontos1);
    printf("Os dados da carta 01 são: \n");
    printf("Estado: %s\n", estado);
    printf("Código da carta: %s\n", codigo);
    printf("Nome da cidade: %s\n", nome);
    printf("População: %d\n", populacao);
    printf("Área: %.2f\n", area);
    printf("PIB: %.2f\n", pib);
    printf("Número de pontos turísticos: %d\n", pontos);
    printf("Os dados da carta 02 são: \n");
    printf("Estado: %s\n", estado1);
    printf("Código da carta: %s\n", codigo1);
    printf("Nome da cidade: %s\n", nome1);
    printf("População: %d\n", populacao1);
    printf("Área: %.2f\n", area1);
    printf("PIB: %.2f\n", pib1);
    printf("Número de pontos turísticos: %d\n", pontos1);
    return 0;
}
